version: '3.3'
services:
  app:
    build: .
    image: riot-dev
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REDIS=redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"